2017-09-19 15:10:34,885 ERROR 11452 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:11452)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 11452
hostname: v_lljunli-PC0

2017-09-19 15:11:36,599 ERROR 10140 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:10140)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 10140
hostname: v_lljunli-PC0

2017-09-19 15:15:26,930 ERROR 13596 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:13596)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 13596
hostname: v_lljunli-PC0

2017-09-19 15:16:08,357 ERROR 11876 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:11876)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 11876
hostname: v_lljunli-PC0

2017-09-19 15:25:47,038 ERROR 13708 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:13708)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 13708
hostname: v_lljunli-PC0

2017-09-19 15:27:36,724 ERROR 10000 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:10000)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 10000
hostname: v_lljunli-PC0

2017-09-19 15:30:08,441 ERROR 13896 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:13896)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 13896
hostname: v_lljunli-PC0

2017-09-19 15:32:53,370 ERROR 12968 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:12968)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 12968
hostname: v_lljunli-PC0

2017-09-19 15:53:15,491 ERROR 11972 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:11972)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 11972
hostname: v_lljunli-PC0

2017-09-19 15:59:08,786 ERROR 13492 nodejs.EADDRINUSEError: bind EADDRINUSE null:7001 (uncaughtException throw 1 times on pid:13492)
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at listenOnMasterHandle (net.js:1402:16)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:130:20)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
code: 'EADDRINUSE'
errno: 'EADDRINUSE'
syscall: 'bind'
address: null
port: 7001
name: 'EADDRINUSEError'
pid: 13492
hostname: v_lljunli-PC0

2017-09-19 16:13:31,731 ERROR 7352 nodejs.ServerNoResponseError: server 127.0.0.1:61859 no response in 20029ms, maybe the socket is end on the other side. (address: 127.0.0.1:61859)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 7352
hostname: v_lljunli-PC0

2017-09-19 16:14:19,082 ERROR 13012 nodejs.ClusterClientNoResponseError: client no response in 67349ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 13012
hostname: v_lljunli-PC0

2017-09-19 16:21:06,906 ERROR 13592 nodejs.ServerNoResponseError: server 127.0.0.1:64035 no response in 20019ms, maybe the socket is end on the other side. (address: 127.0.0.1:64035)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 13592
hostname: v_lljunli-PC0

2017-09-19 16:25:01,706 ERROR 3136 nodejs.ServerNoResponseError: server 127.0.0.1:61753 no response in 20012ms, maybe the socket is end on the other side. (address: 127.0.0.1:61753)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 3136
hostname: v_lljunli-PC0

2017-09-19 16:26:21,395 ERROR 13960 nodejs.ClusterClientNoResponseError: client no response in 99688ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 13960
hostname: v_lljunli-PC0

2017-09-19 16:29:41,467 ERROR 3136 nodejs.ServerNoResponseError: server 127.0.0.1:61753 no response in 39993ms, maybe the socket is end on the other side. (address: 127.0.0.1:61753)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 3136
hostname: v_lljunli-PC0

2017-09-19 16:31:14,248 ERROR 13960 nodejs.ClusterClientNoResponseError: client no response in 132781ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 13960
hostname: v_lljunli-PC0

2017-09-19 16:53:31,892 ERROR 14932 nodejs.ServerNoResponseError: server 127.0.0.1:65336 no response in 20020ms, maybe the socket is end on the other side. (address: 127.0.0.1:65336)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 14932
hostname: v_lljunli-PC0

2017-09-19 16:55:25,320 ERROR 14664 nodejs.ServerNoResponseError: server 127.0.0.1:54476 no response in 37094ms, maybe the socket is end on the other side. (address: 127.0.0.1:54476)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 14664
hostname: v_lljunli-PC0

2017-09-19 16:57:38,426 ERROR 15156 nodejs.ClusterClientNoResponseError: client no response in 173105ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 15156
hostname: v_lljunli-PC0

2017-09-19 16:59:18,496 ERROR 14664 nodejs.ServerNoResponseError: server 127.0.0.1:54476 no response in 39994ms, maybe the socket is end on the other side. (address: 127.0.0.1:54476)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\tcp-base\lib\base.js:422:21)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ServerNoResponseError'
pid: 14664
hostname: v_lljunli-PC0

2017-09-19 17:16:30,746 ERROR 15156 nodejs.ClusterClientNoResponseError: client no response in 1092250ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\web\unhappy\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
name: 'ClusterClientNoResponseError'
pid: 15156
hostname: v_lljunli-PC0

